package Task.Exception;

public class ThrowAndThrows{
	public static void main(String[] args) {
		
	}
}